// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_A1h8g3PGVDIdUfZxaTR4xoyAizZwj3I',
    appId: '1:700799021968:web:12e925a5f82f90fff27915',
    messagingSenderId: '700799021968',
    projectId: 'p2-andre',
    authDomain: 'p2-andre.firebaseapp.com',
    storageBucket: 'p2-andre.firebasestorage.app',
    measurementId: 'G-CX1DN5RNZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA59giIEQeyQQ9hhHMIO00WIeSyVHYJ04U',
    appId: '1:700799021968:android:46ad8dec16ed327af27915',
    messagingSenderId: '700799021968',
    projectId: 'p2-andre',
    storageBucket: 'p2-andre.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_A1h8g3PGVDIdUfZxaTR4xoyAizZwj3I',
    appId: '1:700799021968:web:6d4fdc23bc14186ff27915',
    messagingSenderId: '700799021968',
    projectId: 'p2-andre',
    authDomain: 'p2-andre.firebaseapp.com',
    storageBucket: 'p2-andre.firebasestorage.app',
    measurementId: 'G-PB6M12F2KM',
  );
}
